FROM debian:bullseye-slim as build

ENV DEBIAN_FRONTEND=noninteractive \
  LANG=en_US.UTF-8

WORKDIR /usr/src/app

RUN apt-get -y update &&\
  apt-get -y install --no-install-recommends\
  python3 python3-pip python3-setuptools ca-certificates &&\
  apt-get -y clean &&\
  apt-get -y autoremove &&\
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* &&\
  truncate -s 0 /var/log/*log

COPY . .


RUN pip3 install . requests 

FROM debian:bullseye-slim

ENV DEBIAN_FRONTEND=noninteractive \
  LANG=en_US.UTF-8 \
  PYTHONDONTWRITEBYTECODE=1 \
  PATH=$PATH:/opt/firefox

ARG firefox_ver=105.0
ARG geckodriver_ver=0.31.0
ARG build_rev=0

RUN apt update &&\
  apt install -y python3 python3-setuptools curl bzip2 &&\
  apt-get install --no-install-recommends --no-install-suggests -y \
  `apt-cache depends firefox-esr | awk '/Depends:/{print$2}'` \
  # additional 'firefox-esl' dependencies which is not in 'depends' list
  libasound2 libxt6 libxtst6 &&\
  curl -fL -o /tmp/firefox.tar.bz2 \
  https://ftp.mozilla.org/pub/firefox/releases/${firefox_ver}/linux-x86_64/en-GB/firefox-${firefox_ver}.tar.bz2 &&\
  tar -xjf /tmp/firefox.tar.bz2 -C /tmp/ &&\
  mv /tmp/firefox /opt/firefox &&\
  # Download and install geckodriver
  curl -fL -o /tmp/geckodriver.tar.gz \
  https://github.com/mozilla/geckodriver/releases/download/v${geckodriver_ver}/geckodriver-v${geckodriver_ver}-linux64.tar.gz &&\
  tar -xzf /tmp/geckodriver.tar.gz -C /tmp/ &&\
  chmod +x /tmp/geckodriver &&\
  mv /tmp/geckodriver /usr/local/bin/ &&\
  apt clean -yq &&\
  apt autoremove -yq &&\
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* &&\
  truncate -s 0 /var/log/*log

COPY --from=build /usr/local/lib/python3.9/dist-packages/ /usr/local/lib/python3.9/dist-packages/
COPY --from=build /usr/local/bin/wapiti /usr/local/bin/wapiti-getcookie /usr/local/bin/

COPY ./tests/integration/wapiti/test.py /usr/local/bin/test.py
COPY ./tests/integration/wapiti/templates_and_data.py /usr/local/bin/templates_and_data.py
COPY ./tests/integration/wapiti/misc_functions.py /usr/local/bin/misc_functions.py
COPY ./tests/integration/wapiti/modules.json /usr/local/bin/modules.json

# Required to test external script for crawler auth, 
# comment the 2 following lines if you removed test_crawler_auth integration tests for any reason
COPY ./tests/integration/test_crawler_auth/external_script_crawler_auth_test.py /usr/local/bin/external_script_crawler_auth_test.py
COPY ./tests/integration/test_crawler_auth/stored_cookie.json  /usr/local/bin/stored_cookie.json

ENTRYPOINT [ "python3","-u","/usr/local/bin/test.py"]
